#ifndef BIT_MATH_H
#define BIT_MATH_H

#define SET_BIT(REG,BIT_NUMBER) REG|=(1<< BIT_NUMBER)
#define CLR_BIT(REG,BIT_NUMBER) REG&=~(1<< BIT_NUMBER)
#define TOG_BIT(REG,BIT_NUMBER) REG^=(1<< BIT_NUMBER)
#define GET_BIT(REG,BIT_NUMBER) ((REG & (1<< BIT_NUMBER))>>BIT_NUMBER)



#endif
